name: alice_example
description: Demonstrates how to use the Alice plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: 4.0.5
  path_provider: 2.0.9

dependency_overrides:
  platform: 3.1.0

dev_dependencies:
  build_runner: 2.1.10
  chopper_generator: 4.0.5
  alice:
    path: ../

flutter:
  uses-material-design: true
